### ISSUE TITLE
Illegal string offset "href"

### ISSUE THREAD

**Issue by jahir3819** [paypal/marketplaces-connectedpath-php-demo#2]
I have successfully installed this code in to XAMPP. Updated PayPalconfig parameters.

When i ran Merchant Onboard options. Faced the below error.

Warning: Illegal string offset 'href' in C:\xampp\htdocs\marketplaces-connectedpath-php-demo-master\businessLogic\connected6.php on line 42

**Comment by schitre1** [comment]
It means the API call is not returning the links in its response, the API response may be an error. Have you tried printing the API response? If you are seeing any error there, please report the error msg back here. That would be helpful in finding the root cause of the issue. Also, ensure that the partner credentials in paypalConfig.php are correct.

**Comment by schitre1** [comment]
Closing the issue due to inactivity.
